# Generated by Django 4.2.9 on 2024-02-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the thermocouple', max_length=50, unique=True)),
                ('Fan_Speed', models.IntegerField(blank=True, help_text='Temperature of the thermocouple in degrees Celsius', null=True)),
                ('Dryer_Speed', models.IntegerField(blank=True, help_text='Temperature of the thermocouple in degrees Celsius', null=True)),
                ('Burner_Speed', models.IntegerField(blank=True, help_text='Temperature of the thermocouple in degrees Celsius', null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
