# Generated by Django 4.2.9 on 2024-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='Durations',
            field=models.IntegerField(blank=True, help_text='Temperature of the thermocouple in degrees Celsius', null=True),
        ),
    ]
