# Generated by Django 4.2.9 on 2024-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_conditions_durations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='Burner_Speed',
            field=models.FloatField(blank=True, help_text='Speed for Burner', null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='Dryer_Speed',
            field=models.FloatField(blank=True, help_text='Speed for Dryer', null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='Durations',
            field=models.IntegerField(blank=True, help_text='Duration to keep car in main firing zone ', null=True),
        ),
        migrations.AlterField(
            model_name='conditions',
            name='Fan_Speed',
            field=models.FloatField(blank=True, help_text='Speed for Fan', null=True),
        ),
    ]
