# Generated by Django 4.2.9 on 2024-02-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0003_alter_conditions_burner_speed_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='conditions',
            new_name='condition',
        ),
    ]
